[global]
# Streamlit configuration for the Yahoo Fantasy Baseball app

# Development mode settings
developmentMode = false

# Server configuration
[server]
# Port for local development
port = 8501

# Enable CORS for local development
enableCORS = false

# Enable XSS protection
enableXsrfProtection = true

# Theme configuration
[theme]
# Force dark theme
base = "dark"
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

# Browser configuration
[browser]
# Automatically open browser on startup (local development)
gatherUsageStats = false

# Logger configuration
[logger]
level = "info"