[global]
# Streamlit configuration for the Yahoo Fantasy Baseball app

# Development mode settings
developmentMode = false

# Server configuration
[server]
# Port for local development
port = 8501

# Enable CORS for local development
enableCORS = false

# Enable XSS protection
enableXsrfProtection = true

# Theme configuration
[theme]
# Use light theme by default
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

# Browser configuration
[browser]
# Automatically open browser on startup (local development)
gatherUsageStats = false

# Logger configuration
[logger]
level = "info"